grafana:
  enabled: true

  admin:
    existingSecret: grafana-admin
    userKey: admin-user
    passwordKey: admin-password

  service:
    type: ClusterIP

prometheus:
  enabled: true

  prometheusSpec:
    retention: 15d

    resources:
      requests:
        cpu: 250m
        memory: 512Mi
      limits:
        cpu: 1
        memory: 2Gi

alertmanager:
  enabled: true

  alertmanagerSpec:
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 500m
        memory: 512Mi

nodeExporter:
  enabled: true

kubeStateMetrics:
  enabled: true
