apiVersion: apps/v1
kind: Deployment
metadata:
  name: server1-blue
  namespace: homelab-apps
  labels:
    app: server1
    version: blue
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server1
      version: blue
  template:
    metadata:
      labels:
        app: server1
        version: blue
    spec:
      imagePullSecrets:
        - name: ghcr-secret

      containers:
        - name: server1
          image: ghcr.io/shaunsphere/hello-server1:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 5
