apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aws-k3s-apps
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/shaunsphere/devops-ai-platform-demo.git
    targetRevision: main
    path: gitops/clusters/aws-cluster
  destination:
    name: aws-k3s-cluster
    namespace: aws-apps
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
